# constants.py

EN_TO_ES = {
    'Afghanistan': 'Afganistán',
    'Albania': 'Albania',
    'Algeria': 'Argelia',
    'Angola': 'Angola',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaiyán',
    'Bahrain': 'Baréin',
    'Bangladesh': 'Bangladés',
    'Barbados': 'Barbados',
    'Belarus': 'Bielorrusia',
    'Belgium': 'Bélgica',
    'Belize': 'Belice',
    'Benin': 'Benín',
    'Bolivia': 'Bolivia',
    'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
    'Botswana': 'Botsuana',
    'Brazil': 'Brasil',
    'Bulgaria': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Bhutan': 'Bután',
    'Cambodia': 'Camboya',
    'Cameroon': 'Camerún',
    'Canada': 'Canada',
    'Chad': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Cyprus': 'Chipre',
    'Colombia': 'Colombia',
    'South Korea': 'Corea del Sur',
    'Costa Rica': 'Costa Rica',
    'Ivory Coast': 'Costa de Marfil',
    'Croatia': 'Croacia',
    'Cuba': 'Cuba',
    'Denmark': 'Dinamarca',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egipto',
    'El Salvador': 'El Salvador',
    'United Arab Emirates': 'Emiratos Árabes Unidos',
    'Eritrea': 'Eritrea',
    'Slovakia': 'Eslovaquia',
    'Slovenia': 'Eslovenia',
    'Spain': 'España',
    'United States': 'Estados Unidos',
    'Estonia': 'Estonia',
    'Ethiopia': 'Etiopía',
    'Philippines': 'Filipinas',
    'Finland': 'Finlandia',
    'France': 'Francia',
    'Gabon': 'Gabón',
    'Georgia': 'Georgia',
    'Ghana': 'Ghana',
    'Greece': 'Grecia',
    'Guadeloupe': 'Guadalupe',
    'Guatemala': 'Guatemala',
    'French Guiana': 'Guayana Francesa',
    'Guinea': 'Guinea',
    'Equatorial Guinea': 'Guinea Ecuatorial',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haití',
    'Honduras': 'Honduras',
    'Hong Kong': 'Hong Kong',
    'Hungary': 'Hungría',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iraq': 'Irak',
    'Ireland': 'Irlanda',
    'Iran': 'Irán',
    'Israel': 'Israel',
    'Italy': 'Italia',
    'Jamaica': 'Jamaica',
    'Japan': 'Japón',
    'Jordan': 'Jordania',
    'Kazakhstan': 'Kazajistán',
    'Kenya': 'Kenia',
    'Kyrgyzstan': 'Kirguistán',
    'Kuwait': 'Kuwait',
    'Laos': 'Laos',
    'Lesotho': 'Lesoto',
    'Liberia': 'Liberia',
    'Libya': 'Libia',
    'Lithuania': 'Lituania',
    'Luxembourg': 'Luxemburgo',
    'Lebanon': 'Líbano',
    'Macedonia': 'Macedonia',
    'Madagascar': 'Madagascar',
    'Malaysia': 'Malasia',
    'Mali': 'Mali',
    'Morocco': 'Marruecos',
    'Martinique': 'Martinica',
    'Mauritania': 'Mauritania',
    'Moldova': 'Moldavia',
    'Mongolia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar (Birmania)',
    'Mexico': 'México',
    'Namibia': 'Namibia',
    'Nepal': 'Nepal',
    'Nicaragua': 'Nicaragua',
    'Nigeria': 'Nigeria',
    'Norway': 'Noruega',
    'New Zealand': 'Nueva Zelanda',
    'Niger': 'Níger',
    'Oman': 'Omán',
    'Pakistan': 'Pakistán',
    'Panama': 'Panamá',
    'Papua New Guinea': 'Papúa Nueva Guinea',
    'Paraguay': 'Paraguay',
    'Netherlands': 'Países Bajos',
    'Peru': 'Perú',
    'Poland': 'Polonia',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'United Kingdom': 'Reino Unido',
    'Central African Republic': 'República Centroafricana',
    'Czech Republic': 'República Checa',
    'Democratic Republic of the Congo': 'República Democrática del Congo',
    'Dominican Republic': 'República Dominicana',
    'Gambia': 'República de Gambia',
    'Republic of the Congo': 'República del Congo',
    'Rwanda': 'Ruanda',
    'Romania': 'Rumania',
    'Russia': 'Rusia',
    'Senegal': 'Senegal',
    'Serbia': 'Serbia',
    'Sierra Leone': 'Sierra Leona',
    'Singapore': 'Singapur',
    'Syria': 'Siria',
    'Somalia': 'Somalia',
    'Sri Lanka': 'Sri Lanka',
    'Eswatini': 'Suazilandia',
    'South Africa': 'SudAfrica',
    'Sudan': 'Sudán',
    'South Sudan': 'Sudán del Sur',
    'Sweden': 'Suecia',
    'Switzerland': 'Suiza',
    'Suriname': 'Surinam',
    'Western Sahara': 'Sáhara Occidental',
    'Thailand': 'Tailandia',
    'Taiwan': 'Taiwán',
    'Tanzania': 'Tanzania',
    'Tajikistan': 'Tayikistán',
    'Togo': 'Togo',
    'Trinidad and Tobago': 'Trinidad y Tobago',
    'Turkmenistan': 'Turkmenistán',
    'Turkey': 'Turquía',
    'Tunisia': 'Túnez',
    'Ukraine': 'Ucrania',
    'Uganda': 'Uganda',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Uzbekistán',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Vietnam',
    'Yemen': 'Yemen',
    'Djibouti': 'Yibuti',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabue',
    'Germany': 'Alemania',
    'Saudi Arabia': 'Arabia Saudí',
}

COUNTRY_REGION_MAP = {
   'Afganistán': 'South Asia', 'Albania': 'Southern Europe', 'Alemania': 'Western Europe',
    'Angola': 'Central Africa', 'Arabia Saudí': 'West Asia', 'Argelia': 'North Africa',
    'Argentina': 'South America', 'Armenia': 'West Asia', 'Australia': 'Oceania',
    'Austria': 'Western Europe', 'Azerbaiyán': 'West Asia', 'Bangladés': 'South Asia',
    'Barbados': 'Caribbean', 'Baréin': 'West Asia', 'Belice': 'Central America',
    'Benín': 'West Africa', 'Bielorrusia': 'Eastern Europe', 'Bolivia': 'South America',
    'Bosnia y Herzegovina': 'Southern Europe', 'Botsuana': 'Southern Africa',
    'Brasil': 'South America', 'Bulgaria': 'Eastern Europe', 'Burkina Faso': 'West Africa',
    'Burundi': 'East Africa', 'Bután': 'South Asia', 'Bélgica': 'Western Europe',
    'Camboya': 'Southeast Asia', 'Camerún': 'Central Africa', 'Canada': 'Canada',
    'Chad': 'Central Africa', 'Chile': 'South America', 'China': 'Eastern Asia',
    'Chipre': 'Southern Europe', 'Colombia': 'South America', 'Corea del Sur': 'Eastern Asia',
    'Costa Rica': 'Central America', 'Costa de Marfil': 'West Africa', 'Croacia': 'Southern Europe',
    'Cuba': 'Caribbean', 'Dinamarca': 'Northern Europe', 'Ecuador': 'South America',
    'Egipto': 'North Africa', 'El Salvador': 'Central America',
    'Emiratos Árabes Unidos': 'West Asia', 'Eritrea': 'East Africa',
    'Eslovaquia': 'Eastern Europe', 'Eslovenia': 'Southern Europe', 'España': 'Southern Europe',
    'Estados Unidos': 'West of USA', 'Estonia': 'Northern Europe', 'Etiopía': 'East Africa',
    'Filipinas': 'Southeast Asia', 'Finlandia': 'Northern Europe', 'Francia': 'Western Europe',
    'Gabón': 'Central Africa', 'Georgia': 'West Asia', 'Ghana': 'West Africa',
    'Grecia': 'Southern Europe', 'Guadalupe': 'Caribbean', 'Guatemala': 'Central America',
    'Guayana Francesa': 'South America', 'Guinea': 'West Africa',
    'Guinea Ecuatorial': 'Central Africa', 'Guinea-Bissau': 'West Africa',
    'Guyana': 'South America', 'Haití': 'Caribbean', 'Honduras': 'Central America',
    'Hong Kong': 'Eastern Asia', 'Hungría': 'Eastern Europe', 'India': 'South Asia',
    'Indonesia': 'Southeast Asia', 'Irak': 'West Asia', 'Irlanda': 'Northern Europe',
    'Irán': 'South Asia', 'Israel': 'West Asia', 'Italia': 'Southern Europe',
    'Jamaica': 'Caribbean', 'Japón': 'Eastern Asia', 'Jordania': 'West Asia',
    'Kazajistán': 'Central Asia', 'Kenia': 'East Africa', 'Kirguistán': 'Central Asia',
    'Kuwait': 'West Asia', 'Laos': 'Southeast Asia', 'Lesoto': 'Southern Africa',
    'Liberia': 'West Africa', 'Libia': 'North Africa', 'Lituania': 'Northern Europe',
    'Luxemburgo': 'Western Europe', 'Líbano': 'West Asia', 'Macedonia': 'Southern Europe',
    'Madagascar': 'East Africa', 'Malasia': 'Southeast Asia', 'Mali': 'West Africa',
    'Marruecos': 'North Africa', 'Martinica': 'Caribbean', 'Mauritania': 'West Africa',
    'Moldavia': 'Eastern Europe', 'Mongolia': 'Eastern Asia', 'Montenegro': 'Southern Europe',
    'Mozambique': 'East Africa', 'Myanmar (Birmania)': 'Southeast Asia',
    'México': 'Central America', 'Namibia': 'Southern Africa', 'Nepal': 'South Asia',
    'Nicaragua': 'Central America', 'Nigeria': 'West Africa', 'Noruega': 'Northern Europe',
    'Nueva Zelanda': 'Oceania', 'Níger': 'West Africa', 'Omán': 'West Asia',
    'Pakistán': 'South Asia', 'Panamá': 'Central America', 'Papúa Nueva Guinea': 'Oceania',
    'Paraguay': 'South America', 'Países Bajos': 'Western Europe', 'Perú': 'South America',
    'Polonia': 'Eastern Europe', 'Portugal': 'Southern Europe', 'Qatar': 'West Asia',
    'Reino Unido': 'Northern Europe', 'República Centroafricana': 'Central Africa',
    'República Checa': 'Eastern Europe', 'República Democrática del Congo': 'Central Africa',
    'República Dominicana': 'Caribbean', 'República de Gambia': 'West Africa',
    'República del Congo': 'Central Africa', 'Ruanda': 'East Africa',
    'Rumania': 'Eastern Europe', 'Rusia': 'Eastern Europe', 'Senegal': 'West Africa',
    'Serbia': 'Eastern Europe', 'Sierra Leona': 'West Africa', 'Singapur': 'Southeast Asia',
    'Siria': 'West Asia', 'Somalia': 'East Africa', 'Sri Lanka': 'South Asia',
    'Suazilandia': 'Southern Africa', 'SudAfrica': 'Southern Africa', 'Sudán': 'North Africa',
    'Sudán del Sur': 'East Africa', 'Suecia': 'Northern Europe', 'Suiza': 'Western Europe',
    'Surinam': 'South America', 'Sáhara Occidental': 'West Africa', 'Tailandia': 'Southeast Asia',
    'Taiwán': 'Eastern Asia', 'Tanzania': 'East Africa', 'Tayikistán': 'Central Asia',
    'Togo': 'West Africa', 'Trinidad y Tobago': 'Caribbean', 'Turkmenistán': 'Central Asia',
    'Turquía': 'West Asia', 'Túnez': 'North Africa', 'Ucrania': 'Eastern Europe',
    'Uganda': 'East Africa', 'Uruguay': 'South America', 'Uzbekistán': 'Central Asia',
    'Venezuela': 'South America', 'Vietnam': 'Southeast Asia', 'Yemen': 'West Asia',
    'Yibuti': 'East Africa', 'Zambia': 'East Africa', 'Zimbabue': 'East Africa',
}

CATEGORY_MAP = {
     'Accessories': 40, 'As Seen on TV!': 16, 'Baby': 60, 'Baseball & Softball': 3,
    'Basketball': 4, 'Books': 59, 'Boxing & MMA': 12, 'CDs': 61, 'Cameras': 62,
    'Camping & Hiking': 43, 'Cardio Equipment': 9, "Children's Clothing": 63,
    'Cleats': 17, 'Computers': 64, 'Consumer Electronics': 65, 'Crafts': 66,
    'DVDs': 67, 'Fishing': 45, 'Fitness Accessories': 11, 'Garden': 68,
    "Girls' Apparel": 26, 'Golf Accessories': 37, 'Golf Apparel': 32,
    'Golf Bags & Carts': 34, 'Golf Balls': 36, 'Golf Gloves': 35, 'Golf Shoes': 33,
    'Health and Beauty': 69, 'Hockey': 7, 'Hunting & Shooting': 44,
    'Indoor/Outdoor Games': 46, "Kids' Golf Clubs": 38, 'Lacrosse': 5,
    "Men's Clothing": 70, "Men's Footwear": 18, "Men's Golf Clubs": 30,
    'Mens/Womens Footwear': 13, 'Music': 71, 'Pet Supplies': 72, 'Shop By Sport': 29,
    'Soccer': 2, 'Sporting Goods': 73, 'Strength Training': 10, 'Tennis & Racquet': 6,
    'Toys': 74, 'Trade-In': 41, 'Video Games': 75, 'Water Sports': 48,
    "Women's Apparel": 24, "Women's Clothing": 76, "Women's Golf Clubs": 31,
}

SHIPPING_DAYS_MAP = {
    'First Class (1 gün / day)': 1,
    'Second Class (2 gün / day)': 2,
    'Same Day (0 gün / day)': 0,
    'Standard Class (4 gün / day)': 4,
}